services:
  llama-server:
    # this was ONLY tested on RTX 3090
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    ports:
      - 8080:8080
    volumes:
      - ~/.cache/llama.cpp:/root/.cache/llama.cpp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      --hf-repo ${HF_REPO:-unsloth/Qwen3.5-4B-GGUF}
      --hf-file ${HF_FILE:-Qwen3.5-4B-Q8_0.gguf}
      -c ${CONTEXT_SIZE:-40960}
      --temp ${TEMPERATURE:-0}
